spring:
  cloud:
    function:
      definition: consumer
    stream:
      bindings:
        consumer-in-0:  # Canal de entrada (Consumidor)
          destination: my-queue
          group: my-test-group
          consumer:
            concurrency: 10 # Número de consumidores concurrentes
            prefetch: 20
        consumer-out-0: # Canal de salida (Productor)
          destination: my-queue
          #consumer:
          #  concurrency: 2 # Número de consumidores concurrentes
          #  maxConcurrency: 2 # Máximo de consumidores concurrentes
          #  prefetch: 20
      #rabbit:
      #  bindings:
      #    consumer-in-0:
      #      consumer:
      #        concurrency: 2 # Número de consumidores concurrentes
      #        maxConcurrency: 2 # Máximo de consumidores concurrentes
      #        prefetch: 20