spring:
  cloud:
    function:
      definition: producer
    stream:
      bindings:
        producer-in-0: # Canal de entrada (Consumidor)
          destination: my-queue
        producer-out-0: # Canal de salida (Productor)
          destination: my-queue
      rabbit:
        #bindings:
        #  producer-in-0:
        #    consumer:
        #      concurrency: 2 # Número de consumidores concurrentes
        #      maxConcurrency: 3 # Máximo de consumidores concurrentes
