
services:
  consumer:
    build: .  # Construye la imagen desde el Dockerfile
    environment:
      URL_BROKER: ${URL_BROKER}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
    deploy:
      replicas: 3  # Lanza 3 instancias automáticamente
      resources:
        limits:
          cpus: "1.0"
          memory: "1g"
    volumes:
      - "/home/rubn/logs:/home/rubn/logs" # Carpeta compartida de logs
    ports:
      - "0:8083"  # Exponemos el puerto
