services:
  producer:
    build: .
    environment:
      URL_BROKER: 192.168.1.27
      USER: rubn
      PASSWORD: password
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "1.0"
          memory: "1g"
    volumes:
      - "/home/rubn/logs:/home/rubn/logs"
