services:
  producer:
    build: .
    environment:
      URL_BROKER: ${URL_BROKER}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "1g"
    volumes:
      - "/home/rubn/logs:/home/rubn/logs"
